
ALTER TABLE public.profiles 
  ADD COLUMN IF NOT EXISTS is_ai_paused BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS credit_balance NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS monthly_budget NUMERIC DEFAULT NULL;
